package server;

public enum GameMessageType {
 GAME_ANSWER_MESSAGE,
 GAME_BOARD_MESSAGE,
 GAME_JOIN_MESSAGE,
 GAME_MOVEMENT_MESSAGE,
 GAME_SETUP_MESSAGE,
 GAME_STATUS_MESSAGE, GAME_LOG_MESSAGE, GAME_TURN_MESSAGE, GAME_SKIP_MESSAGE, GAME_WON_MESSAGE;
}
